#!/usr/bin/env bash

export LC_ALL=C.UTF-8
export LANG=C.UTF-8

version='latest'

docker run -it -p 5002:5002 \
       --device /dev/snd:/dev/snd \
       --user "$(id -u):$(id -g)" \
       -v "${HOME}:${HOME}" \
       -w "${PWD}" \
       "rhasspy/larynx:${version}" \
       --cache-dir /tmp/larynx \
       "$@"
